# Generated by Django 4.2 on 2025-03-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
