# Generated by Django 4.2 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
