# Generated by Django 4.2 on 2025-03-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cateringorder_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringorder',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
