# Generated by Django 4.2 on 2025-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
