# Generated by Django 4.2 on 2025-02-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_foodmenucatering_cateringorder_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringorder',
            name='food_items',
        ),
        migrations.DeleteModel(
            name='FoodMenucatering',
        ),
    ]
