# Generated by Django 4.2 on 2025-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fooditem_remove_cateringorder_menu_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='FoodItemcatering',
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='food_items',
            field=models.ManyToManyField(to='myapp.fooditemcatering'),
        ),
    ]
