# Generated by Django 4.2 on 2025-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_fooditem_fooditemcatering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
