# Generated by Django 4.2 on 2025-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_deliveryaddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
